name: DevOps java thin sample CI

on:
  push:
    branches:
      - master
    paths:
      - pom.xml

jobs:
  check:
    runs-on: ubuntu-latest
    # Default steps
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Check And Test
        run: mvn -B -P jenkins -gs configuration/settings.xml clean test
      - name: Build with Maven
        run: mvn -B -P jenkins -gs configuration/settings.xml -DskipTests clean package
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-cache
          push: true
          tags: |
            kubespheresig/devops-java-sample-cache:latest
            kubespheresig/devops-java-sample-cache:1.0.0
